django_tutorial/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("hello/", include("hello.urls")),
    path("newyear/", include("newyear.urls")),
    path("tasks/", include("tasks.urls")),
]

hello/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:name>", views.greet, name="greet"),
    path("brian/", views.brian, name="brian"),
    path("david/", views.david, name="david")
]

newyear/urls.py
from django.urls import path
from . import views

urlpatterns= [
  path("", views.index, name="index"),
]

tasks/urls.py
from django.urls import path  
from . import views

app_name = "tasks"
urlpatterns = [
  path("", views.index, name="index"),
  path("add/", views.add, name="add"),
]

tasks/models.py
from django.db import models

# Create your models here.

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
  return render(request, "hello/index.html")


def brian(request):
  return HttpResponse("Hello Brian")

def david(request):
  return HttpResponse("Hello David")


def greet(request, name):
  return render(request, "hello/greet.html", {
    "name": name.capitalize()
  })

newyear/views.py
from django.shortcuts import render
import datetime

# Create your views here.
def index(request):
  now = datetime.datetime.now()
  return render(request, "newyear/index.html", {
    "newyear": now.month == 1 and now.day == 1
  })

tasks/views.py
from django.shortcuts import render



tasks = [
  "foo",
  "bar",
  "baz"
]
# Create your views here.
def index(request):
  return render(request, "tasks/index.html", {
    "tasks": tasks
  })

def add(request):
  return render(request, 'tasks/add.html')

hello/templates/hello/greet.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Hello Greet</title>
</head>
<body>
  <h1>Hello {{ name }}</h1>
  
</body>
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello Django</title>
</head>
<body>
  <h1>Hello root page</h1>
</body>
</html>

newyear/templates/newyear/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Is it new years</title>
  <link rel="stylesheet" href="{% static 'newyear/styles.css' %}">
</head>
<body>
    {% if newyear %}
        <h1>Yes</h1>
    {% else %}
        <h1>No</h1>
    {% endif %}
</body>
</html>

tasks/templates/tasks/add.html
{% extends "tasks/layout.html" %}

{% block body%}
    <h1>Add task</h1>
    <form action="">
      <input type="text" name="task">
      <input type="submit" >
    </form>
    <a href="{% url 'tasks:index' %}">View Tasks</a>
{% endblock %}

tasks/templates/tasks/index.html
{% extends "tasks/layout.html" %}

{% block body %}
  <h1>Tasks</h1>
  <ul>
    {% for task in tasks %}
      <li>{{ task }}</li>
    {% endfor %}
  </ul>
  <a href="{% url 'tasks:add' %}">Add Task</a>
{% endblock %}

tasks/templates/tasks/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Tasks</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>